export const songs = [
  {
    id: 1,
    title: 'Acoustic Breeze',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/acousticbreeze.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-acousticbreeze.mp3',
  },
  {
    id: 2,
    title: 'A New Beginning',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/anewbeginning.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-anewbeginning.mp3',
  },
  {
    id: 3,
    title: 'Creative Minds',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/creativeminds.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-creativeminds.mp3',
  },
  {
    id: 4,
    title: 'Cute',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/cute.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-cute.mp3',
  },
  {
    id: 5,
    title: 'Going Higher',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/goinghigher.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-goinghigher.mp3',
  },
  {
    id: 6,
    title: 'Happy Rock',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/happyrock.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-happyrock.mp3',
  },
  {
    id: 7,
    title: 'Jazzy Frenchy',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/jazzyfrenchy.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-jazzyfrenchy.mp3',
  },
  {
    id: 8,
    title: 'Little Idea',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/littleidea.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-littleidea.mp3',
  },
  {
    id: 9,
    title: 'Memories',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/memories.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-memories.mp3',
  },
  {
    id: 10,
    title: 'Moose',
    artist: 'Bensound',
    albumArt: 'https://www.bensound.com/bensound-img/moose.jpg',
    audioSrc: 'https://www.bensound.com/bensound-music/bensound-moose.mp3',
  },
];